### ISSUE TITLE
Java exception on FIJI 

### ISSUE THREAD

**Issue by PMLLancao** [yu-lab-vt/SynQuant#2]
Hello
I followed the instruction to install SynQuant but when I opened the plugin I received an error message ( please, see attached the error)

How can I solve the problem?
I have the last version of Fiji and I using  Windows 10. I will try to do on a MAC too, to see if windows is the problem.

Thank you
Regards
![synquantproblem](https://user-images.githubusercontent.com/24482728/85893384-c8483280-b7c0-11ea-81e2-0881f5938988.PNG)

**Comment by yu-lab-vt** [comment]
Hi,

Thank you for your feedback of SynQuant. 
To use SynQuant, there must be at least one image opened before you open SynQuant. May I know if you have opened an image before using Synquant?

Regards

**Comment by PMLLancao** [comment]
Hello

I just tested again and indeed now work when I have an image open.
Thank you very much.
Kind Regards

On Jun 27, 2020, at 09:54, Yu Lab at Virginia Tech <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,

Thank you for your feedback of SynQuant.
To use SynQuant, there must be at least one image opened before you open SynQuant. May I know if you have opened an image before using Synquant?

Regards
