### ISSUE TITLE
Java CLI/Fiji headless mode for batch processing?

### ISSUE THREAD

**Issue by BioinfoTongLI** [yu-lab-vt/SynQuant#3]
Hello there,

Thank you very much for this wonderful tool!
Just wondering whether there's a chance to have a CLI/Fiji headless version for batch processing?
I know you mentioned in the README that you are working on Matlab version.
However, having a Java CLI/Fiji headless will be much more open-source frendly and potentially will intrigue more people using this great tool. 

Many thanks!
Best,
Tong

**Comment by yu-lab-vt** [comment]
Hi, Tong,

We are not clear what you meant by CLI/Fiji headless version. Can you give us some examples?

**Comment by BioinfoTongLI** [comment]
thanks for you reply!
I mean, for example, running the pre/post/duel-synapse detection without opening the Fiji GUI (once the parameter setting is fixed). See [this](https://imagej.net/learn/headless) for detailed info. Basically, for batch processing a large number of images with out manual clickings.
Best,
Tong

**Comment by yu-lab-vt** [comment]
Hi Tong,

I think your need is batch processing without manual clicks. Running SynQuant through the Fiji Macro script will help you. Please let me know if you have any concerns.

How to use Fiji Macro: 
https://imagej.net/scripting/batch

How to set parameters for SynQuant:
[SynQuant_run_using_macro.pdf](https://github.com/yu-lab-vt/SynQuant/files/7989700/SynQuant_run_using_macro.pdf)

Regards,
Wei Zheng

**Comment by BioinfoTongLI** [comment]
Hi Wei Zheng,

Thank you very much for the detailed instruction!
I agree that Fiji GUI + macro is a great temporaily solution.
Though, you still need to open Fiji GUI to run this.
The good thing about headless mode in fiji is that you can run the processing without GUI opened. It is therefore possible to run it on high performance cluster, e.g. LFS etc.

I will write a macro with the doc you provided, thanks again!
Just wondering are you planning on making any headless version (no GUI). Is the Matlab version that was mentioned in the README also a GUI-dependant version? If so, I can try to create a branch that is headless and create a PR. And in that case could you please kindly provide any directions to where I should start with?

Best,
Tong

**Comment by yu-lab-vt** [comment]
Dear Tong,

Your suggestion is great! We are welcoming everyone to contribute to the project. How about you joining us to work on it? We can discuss the details offline. Send me email to yug@vt.edu.

Guoqiang Yu
Associate Professor
Bradley Department of Electrical & Computer Engineering
Virginia Tech
900 N. Glebe Rd.
Arlington, VA 22203
