### ISSUE TITLE
Null Pointer Exception with an Image Opened

### ISSUE THREAD

**Issue by alexiadi** [yu-lab-vt/SynQuant#4]
Hi,

I noticed that user PMLLancao posted an Issue about the same problem that I'm currently finding with SynQuant.

I have a .tif file open in Fiji, and when I click the SynQuantVid plugin under 'Plugins,' the 3D Particles - Data and Parameter Setting GUI does come up as it should as I've seen in the demo videos you've posted. However, once I click OK on these settings, I receive the same error that PMLLancao discussed:

![image](https://user-images.githubusercontent.com/106185219/170110260-3dbe9840-4a04-4093-a2bd-3945c0043546.png)

I also receive another pop-up 'Log' window saying 'Pixel format not supported.'

![image](https://user-images.githubusercontent.com/106185219/170110483-5359604c-9940-4d2d-8542-0ea98abe25bd.png)

Do you know what the issue may be?

Thank you for developing this plugin and your help!

**Comment by yu-lab-vt** [comment]
@alexiadi Can you send us an example dataset? Let us replicate the error and then figure out the reason.

**Comment by yu-lab-vt** [comment]
@alexiadi You can send the example to yug@vt.edu
