### ISSUE TITLE
SynQuant plugin does not start

### ISSUE THREAD

**Issue by Erdmann-Wolff** [yu-lab-vt/SynQuant#6]
Hi,
I installed the SynQuant-PlugIn as recommended: downloaded the jar-file and put it into the plugin-folder of Fiji. Then I closed Fiji and restarted it, but unfortunately the plug-in does not occur in the "plug-in"-section. I use the following Fiji version: ImajaJ 2.3.0/1.53q; Java 1.8.0_322 (64-bit) on a Mac (macOS Monterey). 
Can you help here?
Looking forward to your answer.
Best,
Ines

**Comment by freemanwyz** [comment]
I just tested it on my Macbook and it looks OK. My Macbook runs MacOS Sonoma.

This is what I just tried, and I am not sure if it works on your computer as well:
1. Download the latest version of Fiji: https://downloads.imagej.net/fiji/latest/fiji-macosx.zip. You can put it anywhere. I just leave it in the download folder.
2. Download the SynQuant JAR file: https://github.com/yu-lab-vt/SynQuant/releases/download/V1.2.8/SynQuantVid_-1.2.8.jar
3. Right-click and open the Fiji package, go to the plugin folder, and put the SynQuant JAR file there.
4. Double-click Fiji, and Mac will tell you it is unsafe. It will also tell you the steps needed to allow Fiji to run if you click the help icon.
5. SynQuant should appear in the plug-in menu, called "SynQuantVid".
